sudo: false
language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "pypy"
    - python: "pypy3"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0; fi
  - pip install tox-travis
script: tox
