cache:
  - '%LOCALAPPDATA%\pip\Cache'

install:
  - python -m pip install -U pip
  - python -m pip install tox
  - python -m pip install -e .

build: false

test_script:
  - SET PYTHONIOENCODING=utf-8
  - tox -e py27,py33,py34,py35,py36,py37
